package com.example.webdbs.controller;

import java.io.IOException;
import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import com.example.webdbs.entity.DuAnBDS;

@Controller
public class ThemDuAnController {

	@GetMapping("/add")
	public String add(@ModelAttribute("duAnBDS") DuAnBDS duAnBDS) {
		return "ThemDuAn";
	}

	@PostMapping("/add")
	public String addDuAn(@ModelAttribute("duAnBDS") DuAnBDS duAnBDS) throws IOException {
		Map asMap = ObjectUtils.asMap("cloud_name", "haminhnhat711", "api_key", "414128439647965",
				"api_secret", "weG0sfQ2m6mxoYuL56aiCKAOIXs", "secure", true);
		System.out.println(duAnBDS.getFile().getBytes());
		
		Cloudinary cloudinary = new Cloudinary(asMap);
			   //fos.close(); There is no more need for this line since you had created the instance of "fos" inside the try. And this will automatically close the OutputStream
		cloudinary.uploader().upload(duAnBDS.getFile(), asMap);
		
		
		return "ThemDuAn";
	}
}
